baseURL = 'https://blog.dkishylau.com/'
languageCode = 'en-us'
title = 'Dzmitry Kishylau'
theme = 'chalk'

[params]
  # chalk theme parameters
  about_enabled = true # Change to true if you wish to show an icon in the navigation that redirects to the about page
  scrollappear_enabled = false
  theme_toggle = false
  rss_enabled = true

  # social network accounts
  twitter = 'dkishylau'
  github = 'ph-ph'
  blog_theme = 'light'
  local_fonts = false

[markup.goldmark.renderer]
  unsafe = true